'use strict';
const steps=window.CODELAB_STEPS;
const videoBase='https://www.youtube.com/watch?v=PHsC_t0j1dU&t=';
const storageKey='abed-codelab-data-engineering-state-v3';
const themeKey='abed-codelab-data-engineering-theme';
let currentIndex=0,state=loadState(),SQL=null,db=null;
const $=id=>document.getElementById(id);
function loadState(){try{const p=JSON.parse(localStorage.getItem(storageKey)||'{}');return{completed:p.completed||{},code:p.code||{}}}catch{return{completed:{},code:{}}}}
function saveState(){localStorage.setItem(storageKey,JSON.stringify(state))}
function secondsFromTimestamp(value){const p=value.split(':').map(Number);if(p.length===2)return p[0]*60+p[1];return p[0]*3600+p[1]*60+p[2]}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function saveCurrentCode(){const s=steps[currentIndex];state.code[s.title]=$('starterCode').value;saveState()}
function renderNav(){$('stepNav').innerHTML='';steps.forEach((s,i)=>{const b=document.createElement('button');b.className='step-link'+(i===currentIndex?' active':'')+(state.completed[s.title]?' complete':'');b.innerHTML='<span class="step-index">'+(state.completed[s.title]?'✓':i+1)+'</span><span class="step-title">'+escapeHtml(s.title)+'</span><span class="step-time">'+escapeHtml(s.time)+'</span>';b.onclick=()=>{saveCurrentCode();currentIndex=i;render();$('sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})};$('stepNav').appendChild(b)})}
function render(){const s=steps[currentIndex];renderNav();$('stepNumber').textContent='Step '+(currentIndex+1)+' of '+steps.length;$('videoTime').textContent='Video '+s.time+' ↗';$('videoTime').href=videoBase+secondsFromTimestamp(s.time)+'s';$('lessonTitle').textContent=s.title;$('lessonIntro').textContent=s.learn;$('learnBullets').innerHTML=s.bullets.map(x=>'<li>'+escapeHtml(x)+'</li>').join('');$('exampleCode').textContent=s.example;$('expectedOutput').textContent=s.output;$('challengeText').textContent=s.challenge;$('solutionCode').textContent=s.solution;$('takeawayText').textContent=s.takeaway;$('starterCode').value=typeof state.code[s.title]==='string'?state.code[s.title]:s.starter;$('solutionPanel').hidden=true;$('checkFeedback').hidden=true;$('runOutput').textContent='Write your answer, then run or check it.';$('completeButton').textContent=state.completed[s.title]?'✓ Complete':'Mark step complete';$('prevButton').disabled=currentIndex===0;$('nextButton').disabled=currentIndex===steps.length-1;const done=Object.values(state.completed).filter(Boolean).length;$('progressText').textContent=done+' of '+steps.length+' complete';$('progressBar').style.width=(done/steps.length*100)+'%'}
function markDone(){const s=steps[currentIndex];state.completed[s.title]=true;saveState();renderNav();$('completeButton').textContent='✓ Complete';const done=Object.values(state.completed).filter(Boolean).length;$('progressText').textContent=done+' of '+steps.length+' complete';$('progressBar').style.width=(done/steps.length*100)+'%'}
function norm(t){return String(t).toLowerCase().replace(/\s+/g,' ').trim()}
function checkText(s){const a=norm($('starterCode').value);const missing=(s.check||[]).filter(x=>!a.includes(norm(x)));return{ok:missing.length===0&&a.length>0,msg:missing.length?'Missing core idea: '+missing[0]:'Correct — your answer contains the key elements.'}}
function resetDb(){if(!SQL)return;if(db)db.close();db=new SQL.Database();db.run(`CREATE TABLE users(user_id INTEGER PRIMARY KEY,full_name TEXT,email TEXT,country TEXT,created_at TEXT);CREATE TABLE orders(order_id INTEGER PRIMARY KEY,user_id INTEGER,order_date TEXT,amount REAL,status TEXT);INSERT INTO users VALUES(1,'Ada Lovelace','ada@example.com','UK','2026-01-05'),(2,'Grace Hopper','grace@example.com','USA','2026-01-12'),(3,'Guido van Rossum','guido@example.com','Netherlands','2026-02-01'),(4,'Margaret Hamilton','margaret@example.com','USA','2026-02-14'),(5,'Linus Torvalds','linus@example.com','Finland','2026-03-01'),(6,'Barbara Liskov','barbara@example.com','USA','2026-03-10');INSERT INTO orders VALUES(101,1,'2026-02-01',120,'paid'),(102,1,'2026-03-15',80,'paid'),(103,2,'2026-02-05',250,'paid'),(104,2,'2026-03-21',40,'cancelled'),(105,3,'2026-03-02',175,'paid'),(106,4,'2026-03-08',320,'paid'),(107,4,'2026-04-01',90,'paid'),(108,5,'2026-04-03',110,'paid');`)}
function execSql(q){resetDb();const r=db.exec(q);return r.length?r[r.length-1]:{columns:[],values:[]}}
function normalizeResult(r){return JSON.stringify({columns:r.columns.map(c=>c.toLowerCase()),values:r.values})}
function table(r){if(!r.columns.length)return 'Query executed successfully.';return '<table><thead><tr>'+r.columns.map(c=>'<th>'+escapeHtml(c)+'</th>').join('')+'</tr></thead><tbody>'+r.values.map(row=>'<tr>'+row.map(v=>'<td>'+escapeHtml(v===null?'NULL':v)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
async function runCurrent(){const s=steps[currentIndex];saveCurrentCode();if(s.type==='sql'){if(!SQL){$('runOutput').textContent='SQL runtime is still loading.';return}try{const r=execSql($('starterCode').value);$('runOutput').innerHTML=table(r);$('executionState').textContent='SQL executed'}catch(e){$('runOutput').textContent=String(e);$('executionState').textContent='SQL error'}}else{$('runOutput').textContent=$('starterCode').value||'(empty answer)';$('executionState').textContent='Preview'}}
async function checkCurrent(){const s=steps[currentIndex],fb=$('checkFeedback');saveCurrentCode();fb.hidden=false;if(s.type==='sql'){if(!SQL){fb.className='check-feedback bad';fb.textContent='SQL runtime is still loading.';return}try{const a=execSql($('starterCode').value),e=execSql(s.sqlSolution||s.solution);$('runOutput').innerHTML=table(a);const ok=normalizeResult(a)===normalizeResult(e);fb.className='check-feedback '+(ok?'good':'bad');fb.textContent=ok?'Correct — your query result matches.':'Not yet — your query runs, but the result does not match the target.';if(ok)markDone()}catch(err){fb.className='check-feedback bad';fb.textContent='SQL error: '+err.message}}else{const r=checkText(s);fb.className='check-feedback '+(r.ok?'good':'bad');fb.textContent=r.msg;if(r.ok)markDone()}}
$('runCode').onclick=runCurrent;$('checkAnswer').onclick=checkCurrent;$('resetCode').onclick=()=>{$('starterCode').value=steps[currentIndex].starter;$('checkFeedback').hidden=true};$('solutionButton').onclick=()=>{$('solutionPanel').hidden=!$('solutionPanel').hidden};$('clearOutput').onclick=()=>{$('runOutput').textContent='';$('checkFeedback').hidden=true};$('prevButton').onclick=()=>{if(currentIndex>0){saveCurrentCode();currentIndex--;render();scrollTo({top:0,behavior:'smooth'})}};$('nextButton').onclick=()=>{if(currentIndex<steps.length-1){saveCurrentCode();currentIndex++;render();scrollTo({top:0,behavior:'smooth'})}};$('completeButton').onclick=()=>{const s=steps[currentIndex];state.completed[s.title]=!state.completed[s.title];saveState();render()};$('resetProgress').onclick=()=>{state={completed:{},code:{}};saveState();render()};$('themeButton').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem(themeKey,d?'light':'dark')};$('menuButton').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('.copy-button').forEach(b=>b.onclick=()=>navigator.clipboard.writeText($(b.dataset.copy).textContent));document.documentElement.dataset.theme=localStorage.getItem(themeKey)||'light';render();initSql();
async function initSql(){try{SQL=await initSqlJs({locateFile:f=>'https://cdn.jsdelivr.net/npm/sql.js@1.13.0/dist/'+f});resetDb();$('runtimeText').textContent='Practice checker + SQL runtime ready'}catch(e){$('runtimeDot').className='runtime-dot';$('runtimeText').textContent='Text checker ready; SQL runtime failed to load'}}